name: engineer
channels:
  - conda-forge
dependencies:
  - ca-certificates
  - certifi
  - fastparquet
  - glum
  - lightgbm
  - optuna
  - xgboost
  - ipython
  - IProgress
  - jupyterlab
  - matplotlib
  - mlflow
  - nb_black
  - openpyxl
  - openssl
  - pandas
  - numpy
  - psycopg2
  - pyarrow
  - python==3.14
  - scikit-learn
  - seaborn
  - plotly
  - geopandas
  - shapely
  - pgcli
  - jupyter
  - tqdm 
  - sqlalchemy
prefix: /opt/homebrew/Caskroom/mambaforge/base/envs/engineer
